// This file is auto-generated by manage-i18n.js
// Do not edit this file directly

export interface MessageSchema {
  navbar: {
    aiConfig: string;
    chat: string;
    worldInfo: string;
    userSettings: string;
    backgrounds: string;
    extensions: string;
    personaManagement: string;
    characterManagement: string;
    recentChats: string;
  };
  formatting: {
    title: string;
    description: string;
  };
  chatManagement: {
    newChat: string;
    createPrompt: string;
    renamePrompt: string;
    deleteConfirmTitle: string;
    deleteConfirmContent: string;
    noRecentChats: string;
    noChatsFound: string;
    scenarioOverride: string;
    scenarioOverridePlaceholder: string;
    connectionProfile: string;
    deleteSelectedConfirmContent: string;
    chatLorebooks: string;
    selectLorebooks: string;
    actions: {
      rename: string;
      export: string;
      import: string;
      delete: string;
    };
    errors: {
      create: string;
      rename: string;
      export: string;
      noActiveChat: string;
      noMessagesToExport: string;
      delete: string;
    };
    tabs: {
      chats: string;
      config: string;
    };
    import: {
      success: string;
      error: string;
    };
  };
  group: {
    peek: string;
    forceTalk: string;
    mute: string;
    addMember: string;
    replyStrategy: string;
    members: string;
    configuration: string;
    queue: string;
    clearQueue: string;
    strategies: {
      manual: string;
      natural: string;
      list: string;
      pooled: string;
    };
    handlingMode: string;
    modes: {
      swap: string;
      joinExclude: string;
      joinInclude: string;
    };
    allowSelfResponses: string;
    autoMode: string;
    autoModeHint: string;
  };
  personaManagement: {
    title: string;
    export: string;
    import: string;
    create: string;
    activated: string;
    noDescription: string;
    currentPersona: string;
    importSuccess: string;
    description: {
      label: string;
      placeholder: string;
    };
    connections: {
      title: string;
      default: string;
      character: string;
      chat: string;
      linkedCharacters: string;
    };
    default: {
      tooltip: string;
    };
    globalSettings: {
      title: string;
      showNotifications: string;
    };
    actions: {
      rename: string;
      syncName: string;
      changeImage: string;
      duplicate: string;
      delete: string;
      syncNameSuccess: string;
    };
    rename: {
      title: string;
      prompt: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      error: string;
    };
    duplicate: {
      error: string;
    };
    lorebooks: {
      label: string;
    };
    errors: {
      importFailed: string;
    };
  };
  worldInfo: {
    activeWorlds: string;
    activeWorldsHint: string;
    globalSettings: string;
    activationSettings: string;
    scanDepth: string;
    contextPercent: string;
    budgetCap: string;
    budgetCapHint: string;
    minActivations: string;
    minActivationsHint: string;
    minActivationsDepthMax: string;
    minActivationsDepthMaxHint: string;
    maxRecursionSteps: string;
    maxRecursionStepsHint: string;
    includeNames: string;
    includeNamesHint: string;
    recursiveScan: string;
    recursiveScanHint: string;
    caseSensitive: string;
    caseSensitiveHint: string;
    matchWholeWords: string;
    matchWholeWordsHint: string;
    useGroupScoring: string;
    useGroupScoringHint: string;
    alertOnOverflow: string;
    alertOnOverflowHint: string;
    newWorld: string;
    import: string;
    export: string;
    rename: string;
    duplicate: string;
    newEntryInBook: string;
    deleteBook: string;
    refresh: string;
    searchPlaceholder: string;
    importSuccess: string;
    totalActiveTokens: string;
    sorting: {
      title: string;
      titleAsc: string;
      titleDesc: string;
      orderAsc: string;
      uidAsc: string;
      uidDesc: string;
    };
    entry: {
      toggle: string;
      titlePlaceholder: string;
      keywordsPlaceholder: string;
      logic: string;
      logicOptions: {
        andAny: string;
        andAll: string;
        notAll: string;
        notAny: string;
      };
      filterPlaceholder: string;
      content: string;
      contentPlaceholder: string;
      positionLabel: string;
      positionTooltip: string;
      positionOptions: {
        beforeChar: string;
        afterChar: string;
        beforeEM: string;
        afterEM: string;
        beforeAN: string;
        afterAN: string;
        atDepthSystem: string;
        outlet: string;
      };
      depth: string;
      order: string;
      trigger: string;
      move: string;
      duplicate: string;
      delete: string;
      additionalSources: string;
      charDescription: string;
      charPersonality: string;
      scenario: string;
      personaDescription: string;
      charNote: string;
      creatorNotes: string;
      entryState: string;
      entryStates: {
        constant: string;
        normal: string;
      };
      delay: string;
      outletName: string;
      groupSettings: string;
      group: string;
      groupWeight: string;
      groupOverride: string;
      recursionSettings: string;
      delayUntilRecursion: string;
      preventRecursion: string;
      excludeRecursion: string;
      characterFilters: string;
      filterCharNames: string;
      filterCharTags: string;
      filterCharExclude: string;
      ignoreBudget: string;
      matchWholeWords: string;
      caseSensitive: string;
    };
    popup: {
      newBookTitle: string;
      newBookContent: string;
      newBookInput: string;
      deleteBookContent: string;
      renameBookTitle: string;
      duplicateBookTitle: string;
      duplicateBookInputSuffix: string;
      deleteEntryTitle: string;
      deleteEntryContent: string;
      importEmbeddedTitle: string;
      importEmbeddedContent: string;
    };
    errors: {
      loadListFailed: string;
      loadFailed: string;
      saveFailed: string;
      createFailed: string;
      deleteFailed: string;
      renameFailed: string;
      bookNotFound: string;
      importFailed: string;
      exportFailed: string;
    };
  };
  backgrounds: {
    add: string;
    fitting: string;
    fittingOptions: {
      classic: string;
      cover: string;
      contain: string;
      stretch: string;
      center: string;
    };
    autoSelect: string;
    autoSelectTooltip: string;
    searchPlaceholder: string;
    systemBackgrounds: string;
    zoomIn: string;
    zoomOut: string;
    confirmDelete: string;
    renameTitle: string;
    actions: {
      lock: string;
      unlock: string;
      rename: string;
      delete: string;
    };
    errors: {
      fetch: string;
      noChatLock: string;
      upload: string;
      delete: string;
      rename: string;
    };
  };
  aiConfig: {
    tabConnections: string;
    tabSampler: string;
    tabPrompts: string;
    promptsTitle: string;
    manualInputNote: string;
    docsLinkTooltip: string;
    topPMinP: string;
    presets: {
      sampler: {
        label: string;
      };
      import: string;
      export: string;
      delete: string;
      update: string;
      rename: string;
      saveAs: string;
      newName: string;
      renamePopupTitle: string;
      deletePopupContent: string;
      errors: {
        renameDefault: string;
        deleteDefault: string;
        noExportSelected: string;
        exportNotFound: string;
        importInvalid: string;
        noPresetName: string;
        migrateFailed: string;
        missingFields: string;
        invalidFieldTypes: string;
      };
      messages: {
        migrateSuccess: string;
        migrateTextCompletion: string;
      };
    };
    promptManager: {
      label: string;
      description: string;
      noPrompts: string;
      newPrompt: string;
      role: string;
      content: string;
      selectFromLibrary: string;
      addFromLibrary: string;
      globalPrompts: string;
      markerHint: string;
    };
    contextSize: {
      label: string;
      unlocked: string;
      unlockedTooltip: string;
    };
    maxResponseLength: {
      label: string;
    };
    streaming: {
      label: string;
      description: string;
    };
    showThoughts: {
      label: string;
      description: string;
    };
    reasoningEffort: {
      label: string;
      tooltip: string;
      options: {
        auto: string;
        minimum: string;
        low: string;
        medium: string;
        high: string;
        maximum: string;
      };
      descriptionOpenAI: string;
      descriptionClaude: string;
      descriptionGoogle: string;
    };
    temperature: {
      label: string;
    };
    freqPenalty: {
      label: string;
    };
    presPenalty: {
      label: string;
    };
    repPenalty: {
      label: string;
    };
    topK: {
      label: string;
    };
    topP: {
      label: string;
    };
    minP: {
      label: string;
    };
    topA: {
      label: string;
    };
    claude: {
      useSysPrompt: {
        label: string;
        description: string;
      };
      assistantPrefill: {
        label: string;
        description: string;
      };
    };
    google: {
      useSysPrompt: {
        label: string;
        description: string;
      };
    };
    koboldcpp: {
      header: string;
      tfs: string;
      typical: string;
      repPenRange: string;
      dynatempRange: string;
      smoothingFactor: string;
      dynatempExponent: string;
      mirostat: {
        label: string;
        disabled: string;
        v1: string;
        v2: string;
      };
      mirostatTau: string;
      mirostatEta: string;
      xtcThreshold: string;
      xtcProbability: string;
      nsigma: string;
      dryMultiplier: string;
      dryBase: string;
      dryAllowedLength: string;
      dryPenaltyLastN: string;
      drySequenceBreakers: string;
      grammar: string;
      grammarRetainState: string;
      bannedTokens: string;
      samplerOrder: string;
      groups: {
        basic: string;
        dynatemp: string;
        mirostat: string;
        xtc: string;
        dry: string;
        tfs: string;
        grammar: string;
      };
    };
    ollama: {
      header: string;
      groups: {
        advanced: string;
      };
      repeatLastN: string;
      numBatch: string;
      numKeep: string;
      tfsZ: string;
      typicalP: string;
    };
    media: {
      send: {
        label: string;
        description: string;
      };
      imageQuality: {
        label: string;
        options: {
          auto: string;
          low: string;
          high: string;
        };
      };
      limits: {
        google: string;
      };
    };
    tools: {
      enable: {
        label: string;
        description: string;
      };
      warning: {
        postProcessing: string;
      };
    };
  };
  userSettings: {
    searchPlaceholder: string;
    noResults: string;
  };
  api: {
    connectSuccess: string;
    connectFailed: string;
    status: {
      bypassed: string;
      valid: string;
      noConnection: string;
      notConnected: string;
      connecting: string;
    };
  };
  errors: {
    csrfToken: string;
  };
  common: {
    ok: string;
    cancel: string;
    cancelled: string;
    save: string;
    expandedEditor: string;
    yes: string;
    close: string;
    no: string;
    none: string;
    global: string;
    loading: string;
    tokens: string;
    confirm: string;
    delete: string;
    deleted: string;
    of: string;
    continue: string;
    search: string;
    clear: string;
    resetToDefaults: string;
    confirmDelete: string;
    by: string;
    reset: string;
    seconds: string;
    remove: string;
    dragToReorder: string;
    dragHandle: string;
    toggle: string;
    refresh: string;
    messages: string;
    noResults: string;
    name: string;
    select: string;
    selected: string;
    selectAll: string;
    chat: string;
    new: string;
    text: string;
    import: string;
    export: string;
    exportActive: string;
    importSingle: string;
    edit: string;
    create: string;
    rename: string;
    activate: string;
    add: string;
    collapseSidebar: string;
    expandSidebar: string;
    loadingButton: string;
    upload: string;
    image: string;
    info: string;
    general: string;
    default: string;
    welcome: string;
    back: string;
    preview: string;
    login: string;
    copy: string;
    regenerate: string;
    expand: string;
    collapse: string;
    model: string;
    clearSelection: string;
    apply: string;
  };
  popup: {
    cropAvatar: {
      title: string;
    };
  };
  secrets: {
    manageKeysFor: string;
    addNewKey: string;
    keySaved: string;
    noKeysFound: string;
    labelPlaceholder: string;
    keyPlaceholder: string;
  };
  pagination: {
    first: string;
    previous: string;
    next: string;
    last: string;
    perPage: string;
    itemsPerPageLabel: string;
  };
  chat: {
    inputPlaceholder: string;
    options: string;
    send: string;
    loadError: string;
    createError: string;
    emptyLog: string;
    groupChat: string;
    loadMoreMessages: string;
    generate: {
      noPrompts: string;
      errorFallback: string;
      noModelError: string;
      noPersonaError: string;
      noSpeaker: string;
      postProcessError: string;
      emptyResponseError: string;
      usingTools: string;
      toolError: string;
      maxRecursionError: string;
    };
    buttons: {
      confirmEdit: string;
      copyMessage: string;
      addReasoning: string;
      deleteMessage: string;
      moveUp: string;
      moveDown: string;
      swipeLeft: string;
      swipeRight: string;
      itemization: string;
      showInPrompt: string;
      hideFromPrompt: string;
      ignoreImage: string;
      unignoreImage: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      confirmMessageWithToolChain: string;
      confirmSwipeMessage: string;
      confirmSwipeMessageWithToolChain: string;
      deleteSwipe: string;
      deleteMessage: string;
      lastSwipeError: string;
      plusOne: string;
      confirmBulkTitle: string;
      confirmBulkContent: string;
    };
    selection: {
      modeFree: string;
      modeRange: string;
      toolbar: string;
    };
    copy: {
      error: string;
    };
    optionsMenu: {
      manageChats: string;
      regenerate: string;
      continue: string;
      selectMessages: string;
    };
    typingIndicator: string;
    abort: string;
    reasoning: {
      title: string;
    };
    itemization: {
      title: string;
      apiModel: string;
      preset: string;
      tokenizer: string;
      disclaimer: string;
      systemInfo: string;
      description: string;
      personality: string;
      scenario: string;
      examples: string;
      persona: string;
      worldInfo: string;
      chatHistory: string;
      extensions: string;
      bias: string;
      totalTokens: string;
      maxContext: string;
      showRaw: string;
      showWorldInfo: string;
      copy: string;
    };
    media: {
      videoTooLong: string;
      metadataError: string;
      tooLarge: string;
      unsupportedType: string;
      notSupported: string;
      unsupportedVision: string;
      unsupportedVideo: string;
      unsupportedAudio: string;
      dropFiles: string;
      uploadError: string;
      attach: string;
    };
    tools: {
      title: string;
      noTools: string;
      disabled: {
        setting: string;
        postProcessing: string;
        model: string;
      };
    };
    toolSteps: {
      title: string;
    };
    quickActions: {
      title: string;
      configure: string;
      layout: string;
      layoutRow: string;
      layoutColumn: string;
      enabledActions: string;
      displayOptions: string;
      showLabels: string;
      showGroupNames: string;
      showDividers: string;
      group: {
        generation: string;
        inputMessage: string;
        contextAI: string;
      };
    };
  };
  character: {
    import: {
      abortedMessage: string;
      unsupportedType: string;
      error: string;
      errorMessage: string;
      tagsImported: string;
      tagsImportedMessage: string;
    };
    save: {
      error: string;
    };
    export: {
      error: string;
    };
    fetch: {
      overflowWarning: string;
    };
    create: {
      error: string;
    };
    delete: {
      confirmTitle: string;
      confirmMessage: string;
      deleteChats: string;
      error: string;
    };
    updateImage: {
      error: string;
    };
    duplicate: {
      error: string;
    };
    tokenWarning: string;
  };
  characterPanel: {
    toolbar: string;
    listLabel: string;
    isFavorite: string;
    createNew: string;
    importFile: string;
    searchToggle: string;
    searchPlaceholder: string;
    filterTags: string;
    bulkSelectToggle: string;
    sorting: {
      title: string;
      nameAsc: string;
      nameDesc: string;
      newest: string;
      oldest: string;
      favorites: string;
      random: string;
    };
    editor: {
      placeholderTitle: string;
      placeholderText: string;
      placeholderButton: string;
    };
    tags: {
      tagName: string;
      manage: string;
      managerTitle: string;
      existing: string;
      noTags: string;
      editTitle: string;
      addTitle: string;
      background: string;
      foreground: string;
      add: string;
      removeColor: string;
    };
    bulkTags: {
      title: string;
      selected: string;
      edit: string;
      selectCharacter: string;
      description: string;
      addTags: string;
      addPlaceholder: string;
      removeTags: string;
      removePlaceholder: string;
    };
  };
  characterEditor: {
    avatar: string;
    favorite: string;
    export: string;
    exportAsPng: string;
    exportAsJson: string;
    duplicate: string;
    delete: string;
    more: string;
    searchTags: string;
    creatorNotes: string;
    toggleSpoiler: string;
    noCreatorNotes: string;
    detailsHidden: string;
    description: string;
    firstMessage: string;
    namePlaceholder: string;
    descriptionPlaceholder: string;
    firstMessagePlaceholder: string;
    openLastChat: string;
    startNewChat: string;
    embeddedLorebook: string;
    tokenCounts: {
      title: string;
      total: string;
      permanent: string;
    };
    stats: {
      title: string;
    };
    moreOptions: {
      importCardLore: string;
      convertToPersona: string;
      rename: string;
    };
    name: string;
    tags: string;
    advanced: {
      promptOverrides: string;
      postHistoryInstructions: string;
      postHistoryInstructionsPlaceholder: string;
      metadata: string;
      metadataHint: string;
      metadataOptional: string;
      createdBy: string;
      createdByPlaceholder: string;
      characterVersion: string;
      characterVersionPlaceholder: string;
      creatorNotes: string;
      creatorNotesPlaceholder: string;
      tagsToEmbed: string;
      tagsToEmbedPlaceholder: string;
      personality: string;
      personalityPlaceholder: string;
      scenario: string;
      scenarioPlaceholder: string;
      characterNote: string;
      characterNotePlaceholder: string;
      depth: string;
      role: string;
      talkativeness: string;
      talkativenessHint: string;
      talkativenessShy: string;
      talkativenessNormal: string;
      talkativenessChatty: string;
      dialogueExamples: string;
      dialogueExamplesPlaceholder: string;
      editingTitle: string;
      roles: {
        system: string;
        user: string;
        assistant: string;
      };
    };
    validation: {
      nameRequired: string;
      avatarRequired: string;
    };
    alternateGreetings: {
      title: string;
      label: string;
      placeholder: string;
      empty: string;
      swapTooltip: string;
    };
  };
  extensions: {
    notifyUpdates: string;
    manage: string;
    install: string;
    managePopupNotImplemented: string;
    installPopupNotImplemented: string;
    placeholder: {
      title: string;
      text: string;
    };
  };
  themes: {
    title: string;
    errors: {
      loadFailed: string;
      saveFailed: string;
      deleteFailed: string;
      importFailed: string;
    };
    variables: {
      colors: {
        textColor: string;
        emphasisColor: string;
        underlineColor: string;
        quoteColor: string;
        emphasisColorUser: string;
        underlineColorUser: string;
        quoteColorUser: string;
        backgroundTint: string;
        chatTint: string;
        userMessageTint: string;
        botMessageTint: string;
        shadowColor: string;
        borderColor: string;
        accentRed: string;
        accentGreen: string;
        warningColor: string;
        errorColor: string;
      };
      scrollbar: {
        width: string;
        thumbColor: string;
        trackColor: string;
        thumbRadius: string;
        trackRadius: string;
        thumbBorderWidth: string;
        thumbShadowColor: string;
      };
      typography: {
        fontSize: string;
        fontFamily: string;
        fontFamilyMono: string;
        borderRadius: string;
        blurStrength: string;
        shadowWidth: string;
      };
      layout: {
        panelWidth: string;
      };
      avatars: {
        width: string;
        height: string;
        borderRadius: string;
      };
    };
  };
  apiConnections: {
    profile: string;
    profileManagement: {
      view: string;
      create: string;
      rename: string;
      delete: string;
      import: string;
      export: string;
      save: string;
      none: string;
      globalActive: string;
      createPopupTitle: string;
      viewPopupTitle: string;
      profileName: string;
      fieldsToInclude: string;
      fieldsIncluded: string;
      renamePopupTitle: string;
      deletePopupContent: string;
      updatedFields: string;
      noChanges: string;
      errors: {
        noSelection: string;
        nameExists: string;
        notFound: string;
      };
    };
    provider: string;
    apiUrl: string;
    secretId: string;
    openaiKey: string;
    claudeKey: string;
    openrouterKey: string;
    mistralaiKey: string;
    groqKey: string;
    customKey: string;
    azureKey: string;
    manageKeys: string;
    keyPrivacy: string;
    openaiModel: string;
    claudeModel: string;
    mistralaiModel: string;
    groqModel: string;
    customModel: string;
    ai21Key: string;
    ai21Model: string;
    aimlapiKey: string;
    aimlapiModel: string;
    cohereKey: string;
    cohereModel: string;
    cometapiKey: string;
    cometapiModel: string;
    deepseekKey: string;
    electronhubKey: string;
    electronhubModel: string;
    fireworksKey: string;
    fireworksModel: string;
    googleKey: string;
    googleModel: string;
    koboldModel: string;
    moonshotKey: string;
    moonshotModel: string;
    nanogptKey: string;
    nanogptModel: string;
    ollamaModel: string;
    ollamaUrl: string;
    perplexityKey: string;
    perplexityModel: string;
    pollinationsModel: string;
    vertexaiKey: string;
    vertexaiModel: string;
    vertexaiProjectId: string;
    vertexaiRegion: string;
    xapiKey: string;
    xaiModel: string;
    zaiKey: string;
    zaiEndpoint: string;
    zaiModel: string;
    customUrl: string;
    azureBaseUrl: string;
    azureDeploymentName: string;
    azureApiVersion: string;
    azureModel: string;
    deepseekModel: string;
    koboldUrl: string;
    providers: {
      openai: string;
      claude: string;
      openrouter: string;
      custom: string;
      ai21: string;
      aimlapi: string;
      azure_openai: string;
      cohere: string;
      deepseek: string;
      electronhub: string;
      fireworks: string;
      groq: string;
      makersuite: string;
      vertexai: string;
      mistralai: string;
      moonshot: string;
      nanogpt: string;
      ollama: string;
      perplexity: string;
      pollinations: string;
      xai: string;
      zai: string;
      koboldcpp: string;
    };
    openrouterModel: string;
    openrouterWebsite: string;
    openrouterOptions: string;
    openrouterUseFallback: string;
    openrouterAllowFallbacks: string;
    openrouterFallbackProviders: string;
    openrouterMiddleout: string;
    formatter: string;
    instruct: {
      title: string;
      create: string;
      edit: string;
      delete: string;
      import: string;
      export: string;
      deleteTitle: string;
      deleteContent: string;
    };
    reasoning: {
      title: string;
      create: string;
      edit: string;
      delete: string;
      import: string;
      export: string;
      deleteContent: string;
      prefix: string;
      suffix: string;
      separator: string;
    };
    middleout: {
      on: string;
      off: string;
      auto: string;
    };
    tokenizer: string;
    tokenizers: {
      auto: string;
      none: string;
      llama: string;
      llama3: string;
      mistral: string;
      yi: string;
      claude: string;
      gemma: string;
      jamba: string;
      qwen2: string;
      commandr: string;
      commanda: string;
      nemo: string;
      deepseek: string;
      gpt2: string;
      gpt35: string;
      gpt4o: string;
    };
    postProcessing: {
      label: string;
      description: string;
      tooltip: string;
      withTools: string;
      noTools: string;
      prompts: {
        none: string;
        merge_tools: string;
        semi_tools: string;
        strict_tools: string;
        merge: string;
        semi: string;
        strict: string;
        single: string;
      };
    };
    instructTemplate: {
      label: string;
      none: string;
    };
    reasoningTemplate: {
      label: string;
      none: string;
    };
    customProxy: {
      title: string;
      createProfile: string;
      deleteProfile: string;
      saveProfile: string;
      renameProfile: string;
      deleteProfileTitle: string;
      deleteProfileContent: string;
      url: string;
      urlPlaceholder: string;
      password: string;
      passwordPlaceholder: string;
    };
    pendingSecretsNote: string;
    testMessage: {
      label: string;
      testing: string;
      success: string;
      failed: string;
      unexpectedStream: string;
    };
  };
  settings: {
    powerUser: {
      spoilerFreeMode: {
        label: string;
        description: string;
      };
      neverResizeAvatars: {
        label: string;
        description: string;
      };
      sendOnEnter: {
        label: string;
        description: string;
        options: {
          disabled: string;
          auto: string;
          enabled: string;
        };
      };
      worldImportDialog: {
        label: string;
        description: string;
      };
      confirmMessageDelete: {
        label: string;
        description: string;
      };
      tagImportSetting: {
        label: string;
        description: string;
        options: {
          none: string;
          all: string;
          only_existing: string;
          ask: string;
        };
      };
    };
    character: {
      hideEmbeddedTagsInPanel: {
        label: string;
        description: string;
      };
      hideEmbeddedTagsInSuggestions: {
        label: string;
        description: string;
      };
    };
    ui: {
      disableAnimations: {
        label: string;
        description: string;
      };
      forceMobileMode: {
        label: string;
        description: string;
      };
      chat: {
        reasoningCollapsed: {
          label: string;
          description: string;
        };
        forbidExternalMedia: {
          label: string;
          description: string;
        };
        messagesToLoad: {
          label: string;
          description: string;
        };
      };
      editor: {
        codeMirrorExpanded: {
          label: string;
          description: string;
        };
        codeMirrorIdentifiers: {
          label: string;
          description: string;
        };
        fields: {
          description: string;
          firstMessage: string;
          personality: string;
          scenario: string;
          characterNote: string;
          dialogueExamples: string;
          postHistoryInstructions: string;
          creatorNotes: string;
          content: string;
          input: string;
          editMessage: string;
          customCss: string;
        };
        groups: {
          character: string;
          persona: string;
          worldInfo: string;
          promptManager: string;
          chat: string;
          theme: string;
        };
      };
    };
    chat: {
      stopOnNameHijack: {
        label: string;
        description: string;
        options: {
          none: string;
          single: string;
          group: string;
          all: string;
        };
      };
      regenerateOnEdit: {
        label: string;
        description: string;
      };
      mergeToolMessages: {
        label: string;
        description: string;
      };
    };
  };
  extensionsBuiltin: {
    chatTranslation: {
      connectionProfile: string;
      connectionProfileHint: string;
      sourceLang: string;
      targetLang: string;
      autoMode: {
        label: string;
        none: string;
        responses: string;
        inputs: string;
        both: string;
      };
      promptTemplate: string;
      promptHint: string;
    };
    bookmarks: {
      sidebarTitle: string;
      header: string;
      noChatLoaded: string;
      noBookmarksYet: string;
      deleteBookmark: string;
      messageNotFound: string;
      messageNumberLabel: string;
      messageNumberPlaceholder: string;
      titleLabel: string;
      titlePlaceholder: string;
      addBookmark: string;
      validationMessageCountMax: string;
    };
    generationTools: {
      rerollButtonLabel: string;
      deleteContinueButtonLabel: string;
      swipeButtonLabel: string;
      impersonateButtonLabel: string;
      generateButtonLabel: string;
      generateDisabled: string;
      generateNoInput: string;
      rerollDisabled: string;
      deleteContinueDisabled: string;
      deletingContinue: string;
      noSnapshot: string;
      contextChanged: string;
      divergenceError: string;
      swipeError: string;
      reverting: string;
      error: string;
      impersonateDisabled: string;
      noPersona: string;
      buildPromptFailed: string;
      noConnectionProfile: string;
      impersonating: string;
      impersonationFailed: string;
      swipeDisabled: string;
      swipeNotApplicable: string;
      swiping: string;
      settings: {
        reset: string;
        rerollEnabled: string;
        deleteContinueEnabled: string;
        impersonateEnabled: string;
        generateEnabled: string;
        swipeEnabled: string;
        impersonateTitle: string;
        connectionProfileLabel: string;
        connectionProfileDesc: string;
        promptLabel: string;
        promptDesc: string;
        generateTitle: string;
        generatePromptDesc: string;
      };
    };
    chatBranching: {
      branchButtonTitle: string;
      branchPointTitle: string;
      rootChatTitle: string;
      rootLabel: string;
      totalMessagesTitle: string;
      createdTitle: string;
      branchTreeTitle: string;
      chatTreeTitle: string;
      noChatLoaded: string;
      branchCreationFailed: string;
      branchName: string;
      loadChatFailed: string;
    };
    rewrite: {
      popupTitle: string;
      popupTitleCharacter: string;
      popupTitleField: string;
      popupTitleMessage: string;
      popupTitleInput: string;
      popupTitleExtension: string;
      settings: {
        defaultConnectionProfile: string;
        templates: string;
        renameTemplate: string;
        duplicateTemplate: string;
        deleteTemplate: string;
        name: string;
        ignoreInput: string;
        ignoreInputHint: string;
        instruction: string;
        customArgs: string;
        noCustomArgs: string;
        addArgument: string;
        templateMacro: string;
        selectTemplate: string;
        resetToDefault: string;
        sessionPreamble: string;
        sessionPreambleHint: string;
        deleteAllSessions: string;
      };
      popup: {
        template: string;
        connectionProfile: string;
        contextPrompt: string;
        escapeMacros: string;
        escapeMacrosHint: string;
        contextMessages: string;
        instruction: string;
        original: string;
        new: string;
        output: string;
        generate: string;
        abort: string;
        apply: string;
        continue: string;
        generating: string;
        oneShot: string;
        sessions: string;
        diff: string;
        showDiff: string;
        generalDiff: string;
        relatedCharacters: string;
        contextCharacters: string;
        contextCharactersDesc: string;
        worldInfoContext: string;
        currentEntry: string;
        contextLorebooks: string;
        contextLorebooksDesc: string;
        allEntries: string;
        structuredResponseFormat: string;
      };
      session: {
        sessions: string;
        noSessions: string;
        sessionItem: string;
        deleteFromHere: string;
        typeMessage: string;
        createFailed: string;
        selectSession: string;
        newSession: string;
        systemInstruction: string;
        toolResult: string;
        toolCalls: string;
        deleteConfirm: string;
      };
      buttons: {
        rewriteMessage: string;
        rewriteInput: string;
        rewriteCharacter: string;
      };
      errors: {
        templateNotFound: string;
        selectProfile: string;
        noConnectionProfile: string;
      };
      messages: {
        generationAborted: string;
        generationFailed: string;
        copiedToClipboard: string;
        copyFailed: string;
        textUpdated: string;
      };
    };
    groupChat: {
      settings: {
        defaultConnectionProfile: string;
        defaultConnectionProfileDesc: string;
        defaultTemplates: string;
        defaultTemplatesDesc: string;
        llmDecisionPrompt: string;
        llmDecisionPromptDesc: string;
        aiSummaryPrompt: string;
        aiSummaryPromptDesc: string;
        summaryInjectionTemplate: string;
        summaryInjectionTemplateDesc: string;
      };
      errors: {
        summaryFailed: string;
        noConnectionProfile: string;
      };
      warnings: {
        missingSummaries: string;
      };
    };
    chatMemory: {
      noProfile: string;
      overlapWarning: string;
      menuItem: string;
      popupTitle: string;
      summarizing: string;
      summarized: string;
      failed: string;
      summarizeButton: string;
      tabs: {
        lorebook: string;
        messages: string;
      };
      labels: {
        connectionProfile: string;
        connectionProfileDesc: string;
        startIndex: string;
        endIndex: string;
        prompt: string;
        result: string;
        targetLorebook: string;
        autoHide: string;
        autoTrigger: string;
      };
      buttons: {
        generate: string;
        create: string;
        reset: string;
        deleteAll: string;
        stop: string;
        clearRange: string;
        resummarize: string;
        summarizeMissing: string;
      };
      placeholders: {
        selectLorebook: string;
        summaryResult: string;
      };
      errors: {
        emptySummary: string;
        bookNotFound: string;
        createFailed: string;
        noMessages: string;
        required: string;
        negative: string;
        outOfBounds: string;
        startGreaterThanEnd: string;
        endLessThanStart: string;
        exceedTotal: string;
        noMatchingMessages: string;
        noSummariesToClear: string;
        noMetadata: string;
      };
      success: {
        memoryCreated: string;
        restored: string;
        cleared: string;
        removedAll: string;
        summarizationComplete: string;
      };
      tooltips: {
        noMemoriesToReset: string;
      };
      popups: {
        reset: {
          title: string;
          content: string;
        };
        summarizeRange: {
          title: string;
          contentAll: string;
          contentMissing: string;
        };
        clearRange: {
          title: string;
          content: string;
        };
        deleteAll: {
          title: string;
          content: string;
        };
      };
      manage: string;
      manageRange: string;
      globalActions: string;
      settings: {
        title: string;
        enable: string;
        autoLabel: string;
        autoDesc: string;
        promptLabel: string;
        promptDesc: string;
        ignoreCountLabel: string;
        ignoreCountDesc: string;
      };
      stats: {
        total: string;
        summarized: string;
      };
      timeline: {
        memory: string;
        selection: string;
        currentSelection: string;
        summarized: string;
        summarizedSingle: string;
      };
    };
    standardTools: {
      network: string;
      corsProxy: string;
      corsProxyHint: string;
      webSearch: string;
      maxResults: string;
      maxResultsHint: string;
      urlInspector: string;
      maxContentLength: string;
      maxContentLengthHint: string;
    };
    liveCommentary: {
      enable: string;
      connectionProfile: string;
      connectionProfileHint: string;
      debounceMs: string;
      displayDurationMs: string;
      promptTemplate: string;
      promptHint: string;
    };
    tracker: {
      status: {
        pending: string;
        success: string;
        error: string;
        idle: string;
      };
      display: {
        title: string;
      };
      popups: {
        createPresetTitle: string;
        newPresetName: string;
        renamePresetTitle: string;
        deletePresetTitle: string;
        deletePresetContent: string;
        selectSchemaTitle: string;
        selectSchemaContent: string;
      };
      toasts: {
        alreadyInProgress: string;
        presetExistsError: string;
        presetCreated: string;
        presetRenamed: string;
        cannotDeleteLastPreset: string;
        presetDeleted: string;
        noConnectionProfile: string;
      };
      chatForm: {
        manageSchemas: string;
      };
    };
    modelRandomizer: {
      enabled: string;
      profile: string;
      selectProfile: string;
      profileEnabled: string;
      setActive: string;
      connectionProfiles: string;
      selectConnectionProfiles: string;
      modelGroups: string;
      addGroup: string;
      groupName: string;
      provider: string;
      models: string;
      selectModels: string;
      noModels: string;
      noModelsLocal: string;
      enterModelId: string;
      manualModelHelp: string;
      randomizeTemperature: string;
      minTemperature: string;
      maxTemperature: string;
      noGroups: string;
      noProfiles: string;
      types: {
        connectionProfiles: string;
        modelGroups: string;
      };
      groups: {
        newGroup: string;
      };
      popups: {
        createProfileTitle: string;
        newProfileName: string;
        selectTypeTitle: string;
        selectTypeContent: string;
        renameProfileTitle: string;
        deleteProfileTitle: string;
        deleteProfileContent: string;
      };
      toasts: {
        profileExists: string;
        profileCreated: string;
        profileRenamed: string;
        profileDeleted: string;
        profileActivated: string;
      };
    };
  };
  login: {
    authenticating: string;
    enterPassword: string;
    selectAccount: string;
    errors: {
      enterUsername: string;
      loginFailed: string;
    };
    messages: {
      loggedInAs: string;
    };
  };
  persona: {
    createFromCharacter: {
      error: string;
    };
  };
  instruct: {
    namesBehavior: {
      none: string;
      force: string;
      include: string;
    };
  };
  a11y: {
    tagInput: {
      description: string;
      tagsList: string;
      removeTag: string;
      addTag: string;
      added: string;
      removed: string;
      suggestionsList: string;
      invalidSelection: string;
    };
    imageCropper: {
      cropBoxLabel: string;
      cropBoxDescription: string;
    };
    pagination: {
      navigation: string;
    };
    backgrounds: {
      images: string;
      scrollToTop: string;
    };
    navbar: {
      navigation: string;
    };
    sidebar: {
      close: string;
      resizeLeft: string;
      resizeRight: string;
      menu: string;
      options: string;
    };
    rangeControl: {
      value: string;
      valueLower: string;
    };
    select: {
      filterOptions: string;
      searchPlaceholder: string;
      noOptions: string;
    };
    smartAvatar: {
      groupAvatar: string;
      singleAvatar: string;
    };
    tabs: {
      list: string;
    };
    codeMirrorEditor: {
      label: string;
    };
  };
}
